// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const decreaseProductStock = `-- name: DecreaseProductStock :one
UPDATE products
SET
    stock = stock - $1 -- Mengurangi stok secara atomik
WHERE
    id = $2
    AND stock >= $1 -- Penjaga anti-overselling
RETURNING id, seller_id, name, price, stock, discount, type, description, created_at, updated_at, deleted_at
`

type DecreaseProductStockParams struct {
	Quantity  int32
	ProductID uuid.UUID
}

func (q *Queries) DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, decreaseProductStock, arg.Quantity, arg.ProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id = $1 
RETURNING id, seller_id, name, price, stock, discount, type, description, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT 
  id,
  seller_id,
  "name",
  price,
  stock,
  discount,
  "type",
  "description",
  created_at,
  updated_at
FROM products
WHERE deleted_at IS NULL
`

type GetAllProductsRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT 
  id,
  seller_id,
  "name",
  price,
  stock,
  discount,
  "type",
  "description",
  created_at,
  updated_at
FROM products
WHERE id = $1 AND deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByIDs = `-- name: GetProductByIDs :many
SELECT 
  id,
  seller_id,
  "name",
  price,
  stock,
  discount,
  "type",
  "description",
  created_at,
  updated_at
FROM products
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

type GetProductByIDsRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetProductByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductByIDsRow
	for rows.Next() {
		var i GetProductByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductStock = `-- name: GetProductStock :one
SELECT stock FROM products WHERE id = $1
`

func (q *Queries) GetProductStock(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getProductStock, id)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const getProductsByName = `-- name: GetProductsByName :many
SELECT 
  id,
  seller_id,
  "name",
  price,
  stock,
  discount,
  "type",
  "description",
  created_at,
  updated_at
FROM products
WHERE name ILIKE $1 AND deleted_at IS NULL
`

type GetProductsByNameRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductsByName(ctx context.Context, name string) ([]GetProductsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByNameRow
	for rows.Next() {
		var i GetProductsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsBySellerID = `-- name: GetProductsBySellerID :many
SELECT 
  id,
  seller_id,
  "name",
  price,
  stock,
  discount,
  "type",
  "description",
  created_at,
  updated_at
FROM products
WHERE seller_id = $1 AND deleted_at IS NULL
`

type GetProductsBySellerIDRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductsBySellerID(ctx context.Context, sellerID uuid.UUID) ([]GetProductsBySellerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsBySellerID, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsBySellerIDRow
	for rows.Next() {
		var i GetProductsBySellerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByType = `-- name: GetProductsByType :many
SELECT 
  id,
  seller_id,
  "name",
  price,
  stock,
  discount,
  "type",
  "description",
  created_at,
  updated_at
FROM products
WHERE "type" = $1 AND deleted_at IS NULL
`

type GetProductsByTypeRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductsByType(ctx context.Context, type_ sql.NullString) ([]GetProductsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByTypeRow
	for rows.Next() {
		var i GetProductsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseProductStock = `-- name: IncreaseProductStock :one
UPDATE products
SET
    stock = stock + $1
WHERE
    id = $2
RETURNING id, seller_id, name, price, stock, discount, type, description, created_at, updated_at, deleted_at
`

type IncreaseProductStockParams struct {
	QuantityToIncrease int32
	ProductID          uuid.UUID
}

func (q *Queries) IncreaseProductStock(ctx context.Context, arg IncreaseProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, increaseProductStock, arg.QuantityToIncrease, arg.ProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
  id, 
  seller_id, 
  "name", 
  price, 
  stock, 
  discount, 
  "type", 
  "description", 
  created_at, 
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
) RETURNING id, seller_id, name, price, stock, discount, type, description, created_at, updated_at, deleted_at
`

type InsertProductParams struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.ID,
		arg.SellerID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.Discount,
		arg.Type,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, price = $3, stock = $4, discount = $5, type = $6, description = $7, updated_at = NOW()
WHERE id = $1 AND seller_id = $8
RETURNING id, seller_id, name, price, stock, discount, type, description, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	SellerID    uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.Discount,
		arg.Type,
		arg.Description,
		arg.SellerID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products SET stock = $2 WHERE id = $1 
RETURNING id, seller_id, name, price, stock, discount, type, description, created_at, updated_at, deleted_at
`

type UpdateProductStockParams struct {
	ID    uuid.UUID
	Stock int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
