// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts WHERE id = $1 AND product_id = $2
`

type DeleteCartParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) DeleteCart(ctx context.Context, arg DeleteCartParams) error {
	_, err := q.db.ExecContext(ctx, deleteCart, arg.ID, arg.ProductID)
	return err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, user_id, product_id, quantity, description, created_at, updated_at FROM carts WHERE user_id = $1 AND product_id = $2
`

type GetCartItemParams struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartItem, arg.UserID, arg.ProductID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT id, user_id, product_id, quantity, description, created_at, updated_at FROM carts WHERE user_id = $1
`

func (q *Queries) GetCartItems(ctx context.Context, userID uuid.UUID) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO carts (id, user_id, product_id, quantity, "description")
VALUES ($1, $2, $3, $4, $5)
`

type InsertCartItemParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ProductID   uuid.UUID
	Quantity    int32
	Description sql.NullString
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCartItem,
		arg.ID,
		arg.UserID,
		arg.ProductID,
		arg.Quantity,
		arg.Description,
	)
	return err
}

const updateCartItem = `-- name: UpdateCartItem :exec
UPDATE carts
SET quantity = $1, "description" = $2
WHERE user_id = $3 AND product_id = $4
`

type UpdateCartItemParams struct {
	Quantity    int32
	Description sql.NullString
	UserID      uuid.UUID
	ProductID   uuid.UUID
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) error {
	_, err := q.db.ExecContext(ctx, updateCartItem,
		arg.Quantity,
		arg.Description,
		arg.UserID,
		arg.ProductID,
	)
	return err
}
