// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ProductID   uuid.UUID
	Quantity    int32
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Order struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Status      string
	OrderDate   time.Time
	TotalAmount sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	Price     int32
}

type Product struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type User struct {
	ID   uuid.UUID
	Name string
}
