// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, user_id, status, order_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOrderParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    string
	OrderDate time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.OrderDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const getOrderByDate = `-- name: GetOrderByDate :many
SELECT id, user_id, status, order_date, total_amount, created_at, updated_at FROM orders WHERE order_date = $1
`

func (q *Queries) GetOrderByDate(ctx context.Context, orderDate time.Time) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderByDate, orderDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.OrderDate,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, order_date, total_amount, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.OrderDate,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByStatus = `-- name: GetOrderByStatus :many
SELECT id, user_id, status, order_date, total_amount, created_at, updated_at FROM orders WHERE status = $1
`

func (q *Queries) GetOrderByStatus(ctx context.Context, status string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.OrderDate,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByUserID = `-- name: GetOrderByUserID :many
SELECT id, user_id, status, order_date, total_amount, created_at, updated_at FROM orders WHERE user_id = $1
`

func (q *Queries) GetOrderByUserID(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.OrderDate,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1, updated_at = $2
WHERE id = $3
`

type UpdateOrderStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateOrderTotalAmount = `-- name: UpdateOrderTotalAmount :exec
UPDATE orders
SET total_amount = $1, updated_at = $2
WHERE id = $3
`

type UpdateOrderTotalAmountParams struct {
	TotalAmount sql.NullInt32
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateOrderTotalAmount(ctx context.Context, arg UpdateOrderTotalAmountParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderTotalAmount, arg.TotalAmount, arg.UpdatedAt, arg.ID)
	return err
}
