// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT 
  products.id,
  products.seller_id,
  users.name as seller_name,
  products.name,
  products.price,
  products.stock,
  products.discount,
  products.type,
  products.description,
  products.created_at,
  products.updated_at
FROM products
LEFT JOIN users ON users.id = products.seller_id
WHERE products.deleted_at IS NULL
`

type GetAllProductsRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	SellerName  sql.NullString
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SellerName,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT 
  products.id,
  products.seller_id,
  users.name as seller_name,
  products.name,
  products.price,
  products.stock,
  products.discount,
  products.type,
  products.description,
  products.created_at,
  products.updated_at
FROM products
LEFT JOIN users ON users.id = products.seller_id
WHERE products.id = $1 AND products.deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	SellerName  sql.NullString
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.SellerName,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductStock = `-- name: GetProductStock :one
SELECT stock FROM products WHERE id = $1
`

func (q *Queries) GetProductStock(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getProductStock, id)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const getProductsByName = `-- name: GetProductsByName :many
SELECT 
  products.id,
  products.seller_id,
  users.name as seller_name,
  products.name,
  products.price,
  products.stock,
  products.discount,
  products.type,
  products.description,
  products.created_at,
  products.updated_at
FROM products
LEFT JOIN users ON users.id = products.seller_id
WHERE products.name LIKE $1 AND products.deleted_at IS NULL
`

type GetProductsByNameRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	SellerName  sql.NullString
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductsByName(ctx context.Context, name string) ([]GetProductsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByNameRow
	for rows.Next() {
		var i GetProductsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SellerName,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsBySellerID = `-- name: GetProductsBySellerID :many
SELECT 
  products.id,
  products.seller_id,
  users.name as seller_name,
  products.name,
  products.price,
  products.stock,
  products.discount,
  products.type,
  products.description,
  products.created_at,
  products.updated_at
FROM products
LEFT JOIN users ON users.id = products.seller_id
WHERE products.seller_id = $1 AND products.deleted_at IS NULL
`

type GetProductsBySellerIDRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	SellerName  sql.NullString
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProductsBySellerID(ctx context.Context, sellerID uuid.UUID) ([]GetProductsBySellerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsBySellerID, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsBySellerIDRow
	for rows.Next() {
		var i GetProductsBySellerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SellerName,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Discount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
  id, seller_id, name, price, stock, discount, type, description, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
)
RETURNING id, seller_id, name, price, stock, discount, type, description, created_at, updated_at, deleted_at
`

type InsertProductParams struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.ID,
		arg.SellerID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.Discount,
		arg.Type,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Discount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = $2, price = $3, stock = $4, discount = $5, type = $6, description = $7, updated_at = NOW()
WHERE id = $1 AND seller_id = $8
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Price       int32
	Stock       int32
	Discount    sql.NullInt32
	Type        sql.NullString
	Description sql.NullString
	SellerID    uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.Discount,
		arg.Type,
		arg.Description,
		arg.SellerID,
	)
	return err
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products SET stock = $2 WHERE id = $1
`

type UpdateProductStockParams struct {
	ID    uuid.UUID
	Stock int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.ExecContext(ctx, updateProductStock, arg.ID, arg.Stock)
	return err
}
